name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:14.13.0
    ports:
      - '4420:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
